name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      # - name: Deploy
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.CF_API_TOKEN }}

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: a574dc0b399103dc329d9a81eb71a095
        run: |
          pnpm add -D wrangler
          pnpm exec wrangler pages deploy public --project-name=buienradar-bot
